2017-08-13 14:52:50,503 - octoprint.server - INFO - Shutting down...
2017-08-13 14:53:00,141 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 14:53:00,170 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 14:53:02,847 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 14:53:02,849 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 14:53:02,867 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 14:53:02,929 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 14:53:07,108 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 14:53:07,441 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 14:53:07,451 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 14:53:07,464 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 14:53:07,467 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 14:53:07,481 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 14:53:07,487 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 14:53:07,516 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 14:53:09,198 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 14:53:09,218 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 14:53:09,224 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 14:53:09,264 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 14:54:14,458 - octoprint.server - INFO - Shutting down...
2017-08-13 14:54:23,531 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 14:54:23,560 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 14:54:26,191 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 14:54:26,194 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 14:54:26,206 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 14:54:26,273 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 14:54:30,598 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 14:54:30,957 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 14:54:30,968 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 14:54:30,981 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 14:54:30,983 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 14:54:30,997 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 14:54:31,001 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 14:54:31,004 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 14:54:32,303 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 14:54:32,323 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 14:54:32,359 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 14:54:32,366 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 14:55:57,723 - octoprint.server - INFO - Shutting down...
2017-08-13 14:55:58,324 - octoprint.server - INFO - Goodbye!
2017-08-13 14:54:23,234 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 14:54:23,264 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 14:54:25,932 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 14:54:25,934 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 14:54:25,952 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 14:54:26,014 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 14:54:30,318 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 14:54:30,686 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 14:54:30,696 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 14:54:30,710 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 14:54:30,713 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 14:54:30,727 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 14:54:30,731 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 14:54:30,735 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 14:54:32,193 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 14:54:32,213 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 14:54:32,219 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 14:54:32,251 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 15:01:06,373 - octoprint.server - INFO - Shutting down...
2017-08-13 14:54:23,331 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 14:54:23,359 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 14:54:25,865 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 14:54:25,867 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 14:54:25,879 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 14:54:25,937 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 14:54:30,134 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 14:54:30,464 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 14:54:30,474 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 14:54:30,487 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 14:54:30,490 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 14:54:30,504 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 14:54:30,508 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 14:54:30,511 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 14:54:31,553 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 14:54:31,573 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 14:54:31,608 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 14:54:31,615 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 15:13:25,463 - octoprint.server - INFO - Shutting down...
2017-08-13 15:13:34,364 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 15:13:34,392 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 15:13:36,924 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 15:13:36,927 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 15:13:36,938 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 15:13:36,997 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 15:13:41,200 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 15:13:41,533 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 15:13:41,543 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 15:13:41,556 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 15:13:41,559 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 15:13:41,572 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 15:13:41,576 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 15:13:41,579 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 15:13:42,530 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 15:13:42,546 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 15:13:42,572 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 15:13:42,577 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 15:16:33,879 - octoprint.server - INFO - Shutting down...
2017-08-13 15:13:35,574 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 15:13:35,605 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 15:13:38,294 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 15:13:38,297 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 15:13:38,308 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 15:13:38,367 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 15:13:42,688 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 15:13:43,051 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 15:13:43,061 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 15:13:43,074 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 15:13:43,076 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 15:13:43,090 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 15:13:43,094 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 15:13:43,097 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 15:13:44,520 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 15:13:44,542 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 15:13:44,578 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 15:13:44,585 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 15:35:39,326 - octoprint.server - INFO - Shutting down...
2017-08-13 15:35:40,054 - octoprint.server - INFO - Goodbye!
2017-08-13 15:35:48,932 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 15:35:48,961 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 15:35:51,743 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 15:35:51,745 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 15:35:51,757 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 15:35:51,816 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 15:35:55,999 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 15:35:56,331 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 15:35:56,341 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 15:35:56,354 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 15:35:56,357 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 15:35:56,370 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 15:35:56,374 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 15:35:56,378 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 15:35:57,326 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 15:35:57,343 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 15:35:57,368 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 15:35:57,373 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 15:54:54,701 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 15:55:15,641 - octoprint.util.pip - INFO - Found pip at /usr/sbin/pip, version is 8.1.2
2017-08-13 15:55:58,528 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2017-08-13 15:56:01,845 - octoprint.plugins.announcements - INFO - Loaded channel _important from http://octoprint.org/feeds/important.xml in 3.3s
2017-08-13 15:58:30,891 - octoprint.plugins.softwareupdate - INFO - Starting update of cost to 0.1.3...
2017-08-13 15:59:02,948 - octoprint.plugins.softwareupdate - ERROR - Update of cost can not be performed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 637, in _perform_update
    update_result = updater.perform_update(target, check, target_version)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 60, in perform_update
    raise exceptions.UpdateError("Error while executing pip install", (stdout, stderr))
UpdateError
2017-08-13 15:59:02,961 - octoprint.plugins.softwareupdate - INFO - Starting update of portlister to 0.1.6...
2017-08-13 15:59:24,045 - octoprint.plugins.softwareupdate - ERROR - Update of portlister can not be performed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 637, in _perform_update
    update_result = updater.perform_update(target, check, target_version)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 60, in perform_update
    raise exceptions.UpdateError("Error while executing pip install", (stdout, stderr))
UpdateError
2017-08-13 15:59:24,049 - octoprint.plugins.softwareupdate - INFO - Starting update of touchui to 0.3.8...
2017-08-13 15:59:52,183 - octoprint.plugins.softwareupdate - ERROR - Update of touchui can not be performed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 637, in _perform_update
    update_result = updater.perform_update(target, check, target_version)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 60, in perform_update
    raise exceptions.UpdateError("Error while executing pip install", (stdout, stderr))
UpdateError
2017-08-13 16:00:34,859 - octoprint.server.api - INFO - Performing command: /home/rhradec/reboot
2017-08-13 16:00:35,203 - octoprint.server.api - WARNING - Command failed with return code -15: 
2017-08-13 16:00:35,225 - octoprint.server - INFO - Shutting down...
2017-08-13 16:00:46,928 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 16:00:46,957 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 16:00:49,866 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 16:00:49,869 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 16:00:49,880 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 16:00:49,942 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 16:00:54,190 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 16:00:54,535 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 16:00:54,545 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 16:00:55,175 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 16:00:55,178 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 16:00:55,193 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 16:00:55,200 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 16:00:55,229 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 16:00:59,494 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on hbot for SSDP
2017-08-13 16:00:59,531 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 16:00:59,563 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 16:00:59,565 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 16:00:59,731 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://hbot.local:5000/'}
2017-08-13 16:12:07,748 - octoprint.server - INFO - Shutting down...
2017-08-13 16:12:20,933 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 16:12:20,964 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 16:12:23,751 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 16:12:23,754 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 16:12:23,766 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 16:12:23,825 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 16:12:28,240 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 16:12:28,603 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 16:12:28,613 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 16:12:28,626 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 16:12:28,629 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 16:12:28,643 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 16:12:28,650 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 16:12:28,671 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 16:12:30,448 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 16:12:30,470 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 16:12:30,473 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 16:12:30,669 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://hbot.local:5000/'}
2017-08-13 16:21:25,811 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 16:26:01,542 - octoprint.server - INFO - Shutting down...
2017-08-13 16:26:10,860 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 16:26:10,892 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 16:26:13,440 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 16:26:13,442 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 16:26:13,454 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 16:26:13,512 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 16:26:17,966 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 16:26:18,305 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 16:26:18,315 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 16:26:18,328 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 16:26:18,330 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 16:26:18,345 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 16:26:18,351 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 16:26:18,372 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 16:26:19,822 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 16:26:19,846 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 16:26:19,849 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on hbot for SSDP
2017-08-13 16:26:19,852 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 16:26:20,069 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://hbot.local:5000/'}
2017-08-13 16:27:41,421 - tornado.application - ERROR - Uncaught exception GET /static/webassets/packed_app.css?758a46c0 (192.168.10.10)
HTTPServerRequest(protocol='http', host='hbot.local:5000', method='GET', uri='/static/webassets/packed_app.css?758a46c0', version='HTTP/1.1', remote_ip='192.168.10.10', headers={'Accept-Language': 'en-US,en;q=0.8,pt-BR;q=0.6,pt;q=0.4', 'Accept-Encoding': 'gzip, deflate', 'Host': 'hbot.local:5000', 'Accept': 'text/css,*/*;q=0.1', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://hbot.local:5000/', 'Cookie': 'session=.eJyrVopPK0otzlCyKikqTdVRis9MUbKqVlJIUrJS8g_xNYrM9cr2Cw_L9q0KNPXN8sqKzMrIjsr1y_UNya6Ico809XX3rYoKD7VVqtVRykxJzSvJLKnUSywtyYgvqSxIVbLKK83JQZJBMj05N6MyMjwoJ7LcFqy7tDi1KB6nfC0Ay_Y4og.DHJxsg.KdOtGJ8aRxg2mmwAs3AOeIu_ZM8'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1334, in _execute
    result = yield result
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 2172, in get
    yield self.flush()
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 111, in result
    raise self._exception
StreamClosedError
2017-08-13 16:27:41,444 - tornado.general - ERROR - Cannot send error response after headers written
2017-08-13 16:27:41,452 - tornado.application - ERROR - Uncaught exception GET /static/webassets/packed_libs.css?6c7d6974 (192.168.10.10)
HTTPServerRequest(protocol='http', host='hbot.local:5000', method='GET', uri='/static/webassets/packed_libs.css?6c7d6974', version='HTTP/1.1', remote_ip='192.168.10.10', headers={'Accept-Language': 'en-US,en;q=0.8,pt-BR;q=0.6,pt;q=0.4', 'Accept-Encoding': 'gzip, deflate', 'Host': 'hbot.local:5000', 'Accept': 'text/css,*/*;q=0.1', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://hbot.local:5000/', 'If-Modified-Since': 'Sun, 13 Aug 2017 22:47:24 GMT', 'If-None-Match': '1502664444', 'Cookie': 'session=.eJyrVopPK0otzlCyKikqTdVRis9MUbKqVlJIUrJS8g_xNYrM9cr2Cw_L9q0KNPXN8sqKzMrIjsr1y_UNya6Ico809XX3rYoKD7VVqtVRykxJzSvJLKnUSywtyYgvqSxIVbLKK83JQZJBMj05N6MyMjwoJ7LcFqy7tDi1KB6nfC0Ay_Y4og.DHJxsg.KdOtGJ8aRxg2mmwAs3AOeIu_ZM8'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1334, in _execute
    result = yield result
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 2172, in get
    yield self.flush()
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 111, in result
    raise self._exception
StreamClosedError
2017-08-13 16:27:41,457 - tornado.general - ERROR - Cannot send error response after headers written
2017-08-13 16:28:51,964 - tornado.application - ERROR - Uncaught exception GET /static/webassets/packed_libs.css?6c7d6974 (192.168.10.10)
HTTPServerRequest(protocol='http', host='hbot.local:5000', method='GET', uri='/static/webassets/packed_libs.css?6c7d6974', version='HTTP/1.1', remote_ip='192.168.10.10', headers={'Accept-Language': 'en-US,en;q=0.8,pt-BR;q=0.6,pt;q=0.4', 'Accept-Encoding': 'gzip, deflate', 'Dnt': '1', 'Host': 'hbot.local:5000', 'Accept': 'text/css,*/*;q=0.1', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'If-Range': '1502666783', 'Connection': 'keep-alive', 'Referer': 'http://hbot.local:5000/', 'Range': 'bytes=1229-137483', 'Cookie': 'session=.eJyrVopPK0otzlCyKikqTdVRis9MUbKqVlJIUrJS8g_xNYrM9cr2Cw_L9q0KNPXN8sqKzMrIjsr1y_UNya6Ico809XX3rYoKD7VVqtVRykxJzSvJLKnUSywtyYgvqSxIVbLKK83JQZJBMj05N6MyMjwoJ7LcFqy7tDi1KB6nfC0Ay_Y4og.DHJx7A.zHLfoarxwlhwABm4vOOubv35MBk'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1334, in _execute
    result = yield result
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 2172, in get
    yield self.flush()
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 111, in result
    raise self._exception
StreamClosedError
2017-08-13 16:28:51,968 - tornado.general - ERROR - Cannot send error response after headers written
2017-08-13 16:28:51,972 - tornado.application - ERROR - Uncaught exception GET /static/webassets/packed_app.css?758a46c0 (192.168.10.10)
HTTPServerRequest(protocol='http', host='hbot.local:5000', method='GET', uri='/static/webassets/packed_app.css?758a46c0', version='HTTP/1.1', remote_ip='192.168.10.10', headers={'Accept-Language': 'en-US,en;q=0.8,pt-BR;q=0.6,pt;q=0.4', 'Accept-Encoding': 'gzip, deflate', 'Host': 'hbot.local:5000', 'Accept': 'text/css,*/*;q=0.1', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://hbot.local:5000/', 'Cookie': 'session=.eJyrVopPK0otzlCyKikqTdVRis9MUbKqVlJIUrJS8g_xNYrM9cr2Cw_L9q0KNPXN8sqKzMrIjsr1y_UNya6Ico809XX3rYoKD7VVqtVRykxJzSvJLKnUSywtyYgvqSxIVbLKK83JQZJBMj05N6MyMjwoJ7LcFqy7tDi1KB6nfC0Ay_Y4og.DHJx7A.zHLfoarxwlhwABm4vOOubv35MBk'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1334, in _execute
    result = yield result
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 2172, in get
    yield self.flush()
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 111, in result
    raise self._exception
StreamClosedError
2017-08-13 16:28:51,976 - tornado.general - ERROR - Cannot send error response after headers written
2017-08-13 16:29:57,783 - octoprint.server - INFO - Shutting down...
2017-08-13 16:29:58,585 - octoprint.server - INFO - Goodbye!
2017-08-13 16:30:07,338 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 16:30:07,369 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 16:30:10,015 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 16:30:10,025 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 16:30:10,037 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 16:30:10,096 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 16:30:14,262 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 16:30:14,720 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 16:30:14,731 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 16:30:14,746 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 16:30:14,748 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 16:30:14,764 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 16:30:14,771 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 16:30:14,796 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 16:30:16,309 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 16:30:16,330 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 16:30:16,332 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on hbot for SSDP
2017-08-13 16:30:16,453 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 16:30:16,508 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://hbot.local:5000/'}
2017-08-13 16:33:58,755 - octoprint.server - INFO - Shutting down...
2017-08-13 16:33:59,359 - octoprint.server - INFO - Goodbye!
2017-08-13 16:34:08,287 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 16:34:08,583 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 16:34:11,464 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 16:34:11,467 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 16:34:11,479 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 16:34:11,547 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 16:34:15,896 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 16:34:16,243 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 16:34:16,253 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 16:34:16,266 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 16:34:16,268 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 16:34:16,283 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 16:34:16,289 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 16:34:16,311 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 16:34:17,562 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 16:34:17,579 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 16:34:17,583 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 16:34:17,758 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://hbot.local:5000/'}
2017-08-13 16:34:27,524 - octoprint.server - INFO - Shutting down...
2017-08-13 16:34:28,184 - octoprint.server - INFO - Goodbye!
2017-08-13 16:34:08,015 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-13 16:34:08,328 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-13 16:34:11,153 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-13 16:34:11,156 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-13 16:34:11,167 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-13 16:34:11,225 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-13 16:34:15,359 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-13 16:34:15,823 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-13 16:34:15,838 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-13 16:34:15,857 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-13 16:34:15,860 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-13 16:34:15,881 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-13 16:34:15,887 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-13 16:34:15,896 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-13 16:34:16,841 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 16:34:16,862 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-13 16:34:16,981 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-13 16:34:17,036 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://hbot.local:5000/'}
2017-08-13 17:08:22,351 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 17:10:08,127 - octoprint.plugins.portlister - WARNING - Not auto connecting because printer is not closed nor in error state.
2017-08-13 17:10:18,275 - octoprint.plugins.portlister - WARNING - Not auto connecting because printer is not closed nor in error state.
2017-08-13 17:10:41,152 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-13 17:10:42,902 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 17:10:59,017 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-13 17:11:00,294 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 17:12:43,820 - octoprint.plugins.portlister - WARNING - Not auto connecting because printer is not closed nor in error state.
2017-08-13 17:12:43,823 - octoprint.plugins.portlister - WARNING - Not auto connecting because printer is not closed nor in error state.
2017-08-13 17:12:55,781 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-13 17:12:57,488 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 17:15:06,730 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-13 17:15:08,498 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 17:16:00,548 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/octoprint/util/__init__.py:546: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if source == target:

2017-08-13 17:16:00,551 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/octoprint/util/__init__.py:564: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value_source != value_target:

2017-08-13 17:16:10,019 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-13 17:16:12,016 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 17:16:49,552 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/octoprint/util/__init__.py:546: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if source == target:

2017-08-13 17:16:49,554 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/octoprint/util/__init__.py:564: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value_source != value_target:

2017-08-13 17:18:58,662 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-13 17:19:00,515 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 17:24:31,353 - octoprint.filemanager.analysis - INFO - Starting analysis of local:bike_holder.0001.dbool_bootleHolder2.gcode
2017-08-13 18:06:21,291 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/octoprint/util/__init__.py:546: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if source == target:

2017-08-13 18:06:21,293 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/octoprint/util/__init__.py:564: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value_source != value_target:

2017-08-13 18:19:12,481 - octoprint.filemanager.analysis - INFO - Starting analysis of local:bike_holder.0001.dbool_bootleHolder2.gcode
2017-08-13 18:23:40,088 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/octoprint/util/__init__.py:546: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if source == target:

2017-08-13 18:23:40,094 - py.warnings - WARNING - /usr/lib/python2.7/site-packages/octoprint/util/__init__.py:564: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value_source != value_target:

2017-08-13 18:23:45,592 - octoprint.filemanager.analysis - INFO - Starting analysis of local:bike_holder.0001.dbool_bootleHolder2.gcode
2017-08-13 20:58:52,378 - octoprint.filemanager.analysis - INFO - Starting analysis of local:bike_holder.0001.dbool_bootleHolder2.gcode
2017-08-13 21:48:13,322 - octoprint.filemanager.analysis - INFO - Starting analysis of local:bike_holder.0001.dbool_bootleHolder2.gcode
2017-08-13 21:50:46,175 - octoprint.filemanager.analysis - INFO - Starting analysis of local:bike_holder.0001.dbool_bootleHolder2.gcode
2017-08-13 21:57:06,792 - octoprint.filemanager.analysis - INFO - Starting analysis of local:bike_holder.0001.dbool_bootleHolder2.gcode
2017-08-13 21:58:24,364 - octoprint.filemanager.analysis - INFO - Starting analysis of local:bike_holder.0001.dbool_bootleHolder2.gcode
2017-08-13 21:59:59,955 - octoprint.filemanager.analysis - INFO - Starting analysis of local:bike_holder.0001.dbool_bootleHolder2.gcode
2017-08-13 22:01:32,946 - octoprint.filemanager.analysis - INFO - Starting analysis of local:bike_holder.0001.dbool_bootleHolder2.gcode
2017-08-13 22:55:34,649 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-13 22:55:35,038 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 22:55:35,307 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 23:27:03,999 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-13 23:28:34,345 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 23:28:40,069 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 23:47:38,141 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-13 23:47:39,886 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-13 23:47:44,419 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-13 23:47:59,543 - tornado.application - ERROR - Uncaught exception GET /downloads/files/local/bike_holder.0001.dbool_bootleHolder2.gcode?ctime=1502686875 (192.168.10.10)
HTTPServerRequest(protocol='http', host='hbot.local:5000', method='GET', uri='/downloads/files/local/bike_holder.0001.dbool_bootleHolder2.gcode?ctime=1502686875', version='HTTP/1.1', remote_ip='192.168.10.10', headers={'Accept-Language': 'en-US,en;q=0.8,pt-BR;q=0.6,pt;q=0.4', 'Accept-Encoding': 'gzip, deflate', 'X-Api-Key': 'E2F1DB946E54457BBB689CCC0B9801B8', 'Host': 'hbot.local:5000', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Cache-Control': 'no-cache', 'Referer': 'http://hbot.local:5000/', 'Cookie': 'session=.eJyrVopPK0otzlCyKikqTdVRis9MUbKqVlJIUrJS8g_xNYrM9cr2Cw_L9q0KNPXN8sqKzMrIjsr1y_UNya6Ico809XX3rYoKD7VVqtVRykxJzSvJLKnUSywtyYgvqSxIVbLKK83JQZJBMj05N6MyMjwoJ7LcFqy7tDi1KB6nfC0Ay_Y4og.DHLUlQ.uluk1ZkRtWYl5h9wUnnHfGewbwA'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1334, in _execute
    result = yield result
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 2172, in get
    yield self.flush()
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 111, in result
    raise self._exception
StreamClosedError
2017-08-13 23:47:59,562 - tornado.general - ERROR - Cannot send error response after headers written
2017-08-14 00:23:28,340 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-14 00:23:30,070 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-14 00:23:31,914 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 00:53:51,239 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-14 00:53:51,564 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-14 00:53:51,965 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 00:55:25,430 - octoprint.filemanager.analysis - INFO - Starting analysis of local:bike_holder.0001.dbool_bootleHolder2.gcode
2017-08-14 00:56:36,177 - octoprint.filemanager.analysis - INFO - Starting analysis of local:spool.001.print_arm2.STL_Model2.STL_Model4.STL_Model3.STL_Model8.STL_Model6.STL_Model7.gcode
2017-08-14 01:01:12,122 - octoprint.server.api - INFO - Performing command: /home/rhradec/halt
2017-08-14 01:01:12,363 - octoprint.server.api - WARNING - Command failed with return code -15: 
2017-08-14 01:01:12,396 - octoprint.server - INFO - Shutting down...
2017-08-14 01:01:12,470 - octoprint.server - INFO - Goodbye!
2017-08-14 01:01:21,683 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-14 01:01:21,711 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-14 01:01:24,192 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-14 01:01:24,194 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-14 01:01:24,205 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-14 01:01:24,287 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-14 01:01:28,711 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-14 01:01:29,047 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-14 01:01:29,057 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-14 01:01:29,069 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-14 01:01:29,071 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-14 01:01:29,085 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-14 01:01:29,091 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-14 01:01:29,111 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-14 01:01:30,337 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on hbot for SSDP
2017-08-14 01:01:30,358 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 01:01:30,376 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-14 01:01:30,378 - octoprint.plugins.portlister - INFO - Port Lister () {}
2017-08-14 01:01:30,773 - octoprint.plugins.announcements - INFO - Loaded channel _important from http://octoprint.org/feeds/important.xml in 0.37s
2017-08-14 01:01:31,872 - octoprint.server - INFO - Preemptively caching / for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://hbot.local:5000/'}
2017-08-14 18:48:26,340 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-14 18:48:28,209 - octoprint.plugins.softwareupdate - ERROR - Could not check active_filters for updates
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 482, in _get_current_version
    information, is_current = version_checker.get_latest(target, check)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 134, in get_latest
    include_prerelease=include_prerelease)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 19, in _get_latest_release
    r = requests.get(RELEASE_URL.format(user=user, repo=repo))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 18:48:28,227 - octoprint.plugins.softwareupdate - ERROR - Could not check touchui for updates
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 482, in _get_current_version
    information, is_current = version_checker.get_latest(target, check)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 134, in get_latest
    include_prerelease=include_prerelease)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 19, in _get_latest_release
    r = requests.get(RELEASE_URL.format(user=user, repo=repo))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 18:48:28,240 - octoprint.plugins.softwareupdate - ERROR - Could not check customcontrol for updates
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 482, in _get_current_version
    information, is_current = version_checker.get_latest(target, check)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 134, in get_latest
    include_prerelease=include_prerelease)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 19, in _get_latest_release
    r = requests.get(RELEASE_URL.format(user=user, repo=repo))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 18:48:28,253 - octoprint.plugins.softwareupdate - ERROR - Could not check portlister for updates
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 482, in _get_current_version
    information, is_current = version_checker.get_latest(target, check)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 134, in get_latest
    include_prerelease=include_prerelease)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 19, in _get_latest_release
    r = requests.get(RELEASE_URL.format(user=user, repo=repo))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 18:48:28,363 - octoprint.plugins.softwareupdate - ERROR - Could not check requestspinner for updates
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 482, in _get_current_version
    information, is_current = version_checker.get_latest(target, check)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 134, in get_latest
    include_prerelease=include_prerelease)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 19, in _get_latest_release
    r = requests.get(RELEASE_URL.format(user=user, repo=repo))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 18:48:28,377 - octoprint.plugins.softwareupdate - ERROR - Could not check cost for updates
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 482, in _get_current_version
    information, is_current = version_checker.get_latest(target, check)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 134, in get_latest
    include_prerelease=include_prerelease)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 19, in _get_latest_release
    r = requests.get(RELEASE_URL.format(user=user, repo=repo))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 18:48:28,390 - octoprint.plugins.softwareupdate - ERROR - Could not check systemcommandeditor for updates
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 482, in _get_current_version
    information, is_current = version_checker.get_latest(target, check)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 134, in get_latest
    include_prerelease=include_prerelease)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 19, in _get_latest_release
    r = requests.get(RELEASE_URL.format(user=user, repo=repo))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 18:48:28,403 - octoprint.plugins.softwareupdate - ERROR - Could not check bqappcompanion for updates
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 482, in _get_current_version
    information, is_current = version_checker.get_latest(target, check)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 134, in get_latest
    include_prerelease=include_prerelease)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 19, in _get_latest_release
    r = requests.get(RELEASE_URL.format(user=user, repo=repo))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 18:48:28,417 - octoprint.plugins.softwareupdate - ERROR - Could not check yamlpatcher for updates
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 482, in _get_current_version
    information, is_current = version_checker.get_latest(target, check)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 134, in get_latest
    include_prerelease=include_prerelease)
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 19, in _get_latest_release
    r = requests.get(RELEASE_URL.format(user=user, repo=repo))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 18:48:28,517 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2017-08-14 18:48:28,602 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 18:48:37,505 - octoprint.plugins.portlister - WARNING - Not auto connecting because printer is not closed nor in error state.
2017-08-14 18:48:37,508 - octoprint.plugins.portlister - WARNING - Not auto connecting because printer is not closed nor in error state.
2017-08-14 18:48:46,360 - octoprint.plugins.portlister - INFO - on_port_created connection_options {'portPreference': '/dev/ttyACM0', 'autoconnect': True, 'baudrates': [115200, 250000, 230400, 57600, 38400, 19200, 9600], 'ports': [], 'baudratePreference': 115200}
2017-08-14 18:48:46,362 - octoprint.plugins.portlister - INFO - Checking if /dev/media0 is in []
2017-08-14 18:48:46,363 - octoprint.plugins.portlister - WARNING - Won't autoconnect because /dev/media0 isn't in []
2017-08-14 18:48:46,381 - octoprint.plugins.portlister - INFO - on_port_created connection_options {'portPreference': '/dev/ttyACM0', 'autoconnect': True, 'baudrates': [115200, 250000, 230400, 57600, 38400, 19200, 9600], 'ports': [], 'baudratePreference': 115200}
2017-08-14 18:48:46,383 - octoprint.plugins.portlister - INFO - Checking if /dev/video0 is in []
2017-08-14 18:48:46,384 - octoprint.plugins.portlister - WARNING - Won't autoconnect because /dev/video0 isn't in []
2017-08-14 18:48:47,210 - octoprint.plugins.portlister - INFO - on_port_created connection_options {'portPreference': '/dev/ttyACM0', 'autoconnect': True, 'baudrates': [115200, 250000, 230400, 57600, 38400, 19200, 9600], 'ports': ['/dev/ttyACM0'], 'baudratePreference': 115200}
2017-08-14 18:48:47,212 - octoprint.plugins.portlister - INFO - Checking if /dev/ttyACM0 is in ['/dev/ttyACM0']
2017-08-14 18:48:47,215 - octoprint.plugins.portlister - INFO - autoconnect_delay 20
2017-08-14 18:49:07,220 - octoprint.plugins.portlister - INFO - do_auto_connect
2017-08-14 18:49:07,223 - octoprint.plugins.portlister - INFO - realpath match
2017-08-14 18:49:07,341 - octoprint.plugins.portlister - INFO - Attempting to connect to /dev/ttyACM0 at 115200 with profile 'hbot'
2017-08-14 18:49:36,267 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-14 18:49:39,441 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-14 18:49:41,502 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 18:53:24,024 - octoprint.filemanager.analysis - INFO - Starting analysis of local:spool.001.STL_Model3.gcode
2017-08-14 18:57:35,624 - octoprint.filemanager.analysis - INFO - Starting analysis of local:spool.001.STL_Model3.gcode
2017-08-14 18:58:12,188 - octoprint.filemanager.analysis - INFO - Starting analysis of local:spool.001.STL_Model3.gcode
2017-08-14 19:02:05,653 - octoprint.filemanager.analysis - INFO - Starting analysis of local:spool.001.STL_Model3.gcode
2017-08-14 19:02:53,909 - octoprint.filemanager.analysis - INFO - Starting analysis of local:spool.001.STL_Model3.gcode
2017-08-14 20:18:40,906 - octoprint.filemanager.analysis - INFO - Starting analysis of local:fanHolder_hradecBot.0001.STL_Model1.gcode
2017-08-14 20:20:04,184 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-14 20:20:06,713 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-14 20:20:10,429 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 20:21:07,300 - octoprint.filemanager.analysis - INFO - Starting analysis of local:fanHolder_hradecBot.0001.polySurface1.gcode
2017-08-14 20:34:13,007 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-14 20:34:14,857 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-14 20:34:16,990 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 20:34:28,627 - octoprint.filemanager.analysis - INFO - Starting analysis of local:fanHolder_hradecBot.0001.STL_Model3.gcode
2017-08-14 20:35:12,873 - tornado.application - ERROR - Uncaught exception GET /downloads/files/local/fanHolder_hradecBot.0001.STL_Model1.gcode?ctime=1502767120 (192.168.10.10)
HTTPServerRequest(protocol='http', host='hbot.local:5000', method='GET', uri='/downloads/files/local/fanHolder_hradecBot.0001.STL_Model1.gcode?ctime=1502767120', version='HTTP/1.1', remote_ip='192.168.10.10', headers={'Accept-Language': 'en-US,en;q=0.8,pt-BR;q=0.6,pt;q=0.4', 'Accept-Encoding': 'gzip, deflate', 'X-Api-Key': '0AF91ECA77954188B3D7281E5F20605A', 'Host': 'hbot.local:5000', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Cache-Control': 'no-cache', 'Referer': 'http://hbot.local:5000/', 'Cookie': 'session=.eJyrVopPK0otzlCyKikqTdVRis9MUbKqVlJIUrJS8g_xNYrM9cr2Cw_L9q0KNPXN8sqKzMrIjsr1y_UNya6Ico809XX3rYoKD7VVqtVRykxJzSvJLKnUSywtyYgvqSxIVbLKK83JQZJBMj05N6MyMjwoJ7LcFqy7tDi1KB6nfC0Ay_Y4og.DHP8sw.t2t9HpTODBVVAdsLhPGhH4xPYvA'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1334, in _execute
    result = yield result
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 2172, in get
    yield self.flush()
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 111, in result
    raise self._exception
StreamClosedError
2017-08-14 20:35:12,909 - tornado.general - ERROR - Cannot send error response after headers written
2017-08-14 20:47:11,472 - octoprint.filemanager.analysis - INFO - Starting analysis of local:fanHolder_hradecBot.0001.STL_Model3.gcode
2017-08-14 20:55:13,091 - octoprint.filemanager.analysis - INFO - Starting analysis of local:fanHolder_hradecBot.0001.STL_Model3.gcode
2017-08-14 20:56:38,506 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.10.10
2017-08-14 20:56:40,405 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.10.10
2017-08-14 20:56:51,088 - octoprint.plugins.announcements - ERROR - Could not fetch channel _important from http://octoprint.org/feeds/important.xml: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/announcements/__init__.py", line 269, in _get_channel_data_from_network
    r = requests.get(url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 21:14:14,118 - octoprint.server.api - INFO - Performing command: /home/rhradec/halt
2017-08-14 21:14:14,384 - octoprint.server.api - WARNING - Command failed with return code -15: 
2017-08-14 21:14:14,451 - octoprint.server - INFO - Shutting down...
2017-08-14 21:14:14,850 - octoprint.server - INFO - Goodbye!
2017-08-14 21:14:23,981 - octoprint.server - INFO - Starting OctoPrint 1.2.15 (HEAD -> master branch)
2017-08-14 21:14:24,010 - octoprint.plugin.core - INFO - Loading plugins from /home/rhradec/.octoprint/plugins, /usr/lib/python2.7/site-packages/octoprint/plugins and installed plugin packages...
2017-08-14 21:14:26,684 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-08-14 21:14:26,686 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 16 mixin implementations, 15 hook handlers
2017-08-14 21:14:26,697 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/rhradec/.octoprint/uploads...
2017-08-14 21:14:26,754 - octoprint.filemanager.storage - INFO - ... file metadata for /home/rhradec/.octoprint/uploads initialized successfully.
2017-08-14 21:14:31,092 - octoprint.util.pip - INFO - Found pip at /bin/pip2, version is 8.1.2
2017-08-14 21:14:31,278 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-14 21:14:31,288 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2017-08-14 21:14:31,998 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Active Filters (0.0.1) = /usr/lib/python2.7/site-packages/octoprint_active_filters
|  Announcement Plugin (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/announcements
|  BQ Android App Companion (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_bqappcompanion
|  Cost Plugin (0.1.2) = /usr/lib/python2.7/site-packages/octoprint_cost
| !CuraEngine (<= 15.04) (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /usr/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/discovery
|  EEPROM Marlin Editor Plugin (0.1.0) = /usr/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  Plugin Manager (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.5) = /usr/lib/python2.7/site-packages/octoprint_portlister
|  RequestSpinner (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_requestspinner
|  ScreenSquish (0.1) = /usr/lib/python2.7/site-packages/octoprint_ScreenSquish
|  Software Update (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  System Command Editor (0.3.1) = /usr/lib/python2.7/site-packages/octoprint_systemcommandeditor
|  TouchUI (0.3.4) = /usr/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /usr/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /usr/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-08-14 21:14:32,000 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-14 21:14:32,014 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-14 21:14:32,020 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/webassets...
2017-08-14 21:14:32,040 - octoprint.server - INFO - Reset webasset folder /home/rhradec/.octoprint/generated/.webassets-cache...
2017-08-14 21:14:33,262 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on hbot for SSDP
2017-08-14 21:14:33,300 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 542, in _fetch_repository_from_url
    r = requests.get(repository_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2017-08-14 21:14:33,315 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-08-14 21:14:33,319 - octoprint.plugins.portlister - INFO - Port Lister () {}
